# Generated by Django 5.2.6 on 2025-09-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alunos',
            new_name='Aluno',
        ),
    ]
